// <auto-generated />
using System;
using Menetlus.Domain;
using Menetlus.External.Contracts;
using Menetlus.Repository.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Menetlus.Repository.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(MenetlusContext))]
    partial class MenetlusContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("order_id_seq");

            modelBuilder.Entity("Menetlus.Domain.Menetlus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('order_id_seq')");

                    b.Property<Avaldaja>("Avaldaja")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Kusimus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Markus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Staatus")
                        .HasColumnType("integer");

                    b.Property<int>("Vastus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("menetlus", (string)null);
                });

            modelBuilder.Entity("Menetlus.Repository.EntityFrameworkCore.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Envelope>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("outbox", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
