//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xtee.Teavitus.Connector.TeavitusTeenus
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://teavitus.x-road.ee", ConfigurationName="Xtee.Teavitus.Connector.TeavitusTeenus.ITeavitusTeenus")]
    public interface ITeavitusTeenus
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XRoadIdentifierType))]
        System.Threading.Tasks.Task<Xtee.Teavitus.Connector.TeavitusTeenus.TeavitaResponse1> TeavitaAsync(Xtee.Teavitus.Connector.TeavitusTeenus.TeavitaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadClientIdentifierType : XRoadIdentifierType
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XRoadLocalGroupIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XRoadGlobalGroupIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XRoadSecurityServerIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XRoadCentralServiceIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XRoadSecurityCategoryIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XRoadServiceIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XRoadClientIdentifierType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadIdentifierType
    {
        
        private string xRoadInstanceField;
        
        private string memberClassField;
        
        private string memberCodeField;
        
        private string subsystemCodeField;
        
        private string groupCodeField;
        
        private string serviceCodeField;
        
        private string serviceVersionField;
        
        private string securityCategoryCodeField;
        
        private string serverCodeField;
        
        private XRoadObjectType objectTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string xRoadInstance
        {
            get
            {
                return this.xRoadInstanceField;
            }
            set
            {
                this.xRoadInstanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string memberClass
        {
            get
            {
                return this.memberClassField;
            }
            set
            {
                this.memberClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string memberCode
        {
            get
            {
                return this.memberCodeField;
            }
            set
            {
                this.memberCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string subsystemCode
        {
            get
            {
                return this.subsystemCodeField;
            }
            set
            {
                this.subsystemCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string groupCode
        {
            get
            {
                return this.groupCodeField;
            }
            set
            {
                this.groupCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string serviceCode
        {
            get
            {
                return this.serviceCodeField;
            }
            set
            {
                this.serviceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string serviceVersion
        {
            get
            {
                return this.serviceVersionField;
            }
            set
            {
                this.serviceVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string securityCategoryCode
        {
            get
            {
                return this.securityCategoryCodeField;
            }
            set
            {
                this.securityCategoryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string serverCode
        {
            get
            {
                return this.serverCodeField;
            }
            set
            {
                this.serverCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public XRoadObjectType objectType
        {
            get
            {
                return this.objectTypeField;
            }
            set
            {
                this.objectTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public enum XRoadObjectType
    {
        
        /// <remarks/>
        MEMBER,
        
        /// <remarks/>
        SUBSYSTEM,
        
        /// <remarks/>
        SERVER,
        
        /// <remarks/>
        GLOBALGROUP,
        
        /// <remarks/>
        LOCALGROUP,
        
        /// <remarks/>
        SECURITYCATEGORY,
        
        /// <remarks/>
        SERVICE,
        
        /// <remarks/>
        CENTRALSERVICE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teavitus.x-road.ee")]
    public partial class Avaldaja
    {
        
        private string eesnimiField;
        
        private string perenimiField;
        
        private string isikukoodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Eesnimi
        {
            get
            {
                return this.eesnimiField;
            }
            set
            {
                this.eesnimiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Perenimi
        {
            get
            {
                return this.perenimiField;
            }
            set
            {
                this.perenimiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Isikukood
        {
            get
            {
                return this.isikukoodField;
            }
            set
            {
                this.isikukoodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teavitus.x-road.ee")]
    public partial class Menetleja
    {
        
        private string isikukoodField;
        
        private string asutuseTunnusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Isikukood
        {
            get
            {
                return this.isikukoodField;
            }
            set
            {
                this.isikukoodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AsutuseTunnus
        {
            get
            {
                return this.asutuseTunnusField;
            }
            set
            {
                this.asutuseTunnusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MenetlusLoppes))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VoetiMenetlusse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VoetiUlevaatamisele))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MenetlusLoodud))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teavitus.x-road.ee")]
    public abstract partial class Teavitus
    {
        
        private string teavitusIdField;
        
        private int menetlusIdField;
        
        private Menetleja menetlejaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TeavitusId
        {
            get
            {
                return this.teavitusIdField;
            }
            set
            {
                this.teavitusIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int MenetlusId
        {
            get
            {
                return this.menetlusIdField;
            }
            set
            {
                this.menetlusIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Menetleja Menetleja
        {
            get
            {
                return this.menetlejaField;
            }
            set
            {
                this.menetlejaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teavitus.x-road.ee")]
    public partial class MenetlusLoppes : Teavitus
    {
        
        private Staatus staatusField;
        
        private Vastus vastusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Staatus Staatus
        {
            get
            {
                return this.staatusField;
            }
            set
            {
                this.staatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Vastus Vastus
        {
            get
            {
                return this.vastusField;
            }
            set
            {
                this.vastusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teavitus.x-road.ee")]
    public enum Staatus
    {
        
        /// <remarks/>
        Ootel,
        
        /// <remarks/>
        Ulevaatamisel,
        
        /// <remarks/>
        Menetluses,
        
        /// <remarks/>
        TagasiLukatud,
        
        /// <remarks/>
        Lopetatud,
    }
    
    /// <remarks/>
    [System.FlagsAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teavitus.x-road.ee")]
    public enum Vastus
    {
        
        /// <remarks/>
        Puudub = 1,
        
        /// <remarks/>
        Jah = 2,
        
        /// <remarks/>
        Ei = 4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teavitus.x-road.ee")]
    public partial class VoetiMenetlusse : Teavitus
    {
        
        private Staatus staatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Staatus Staatus
        {
            get
            {
                return this.staatusField;
            }
            set
            {
                this.staatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teavitus.x-road.ee")]
    public partial class VoetiUlevaatamisele : Teavitus
    {
        
        private Staatus staatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Staatus Staatus
        {
            get
            {
                return this.staatusField;
            }
            set
            {
                this.staatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://teavitus.x-road.ee")]
    public partial class MenetlusLoodud : Teavitus
    {
        
        private Avaldaja avaldajaField;
        
        private string kusimusField;
        
        private string markusField;
        
        private Staatus staatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Avaldaja Avaldaja
        {
            get
            {
                return this.avaldajaField;
            }
            set
            {
                this.avaldajaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Kusimus
        {
            get
            {
                return this.kusimusField;
            }
            set
            {
                this.kusimusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Markus
        {
            get
            {
                return this.markusField;
            }
            set
            {
                this.markusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Staatus Staatus
        {
            get
            {
                return this.staatusField;
            }
            set
            {
                this.staatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadLocalGroupIdentifierType : XRoadIdentifierType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadGlobalGroupIdentifierType : XRoadIdentifierType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadSecurityServerIdentifierType : XRoadIdentifierType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadCentralServiceIdentifierType : XRoadIdentifierType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadSecurityCategoryIdentifierType : XRoadIdentifierType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadServiceIdentifierType : XRoadIdentifierType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://teavitus.x-road.ee")]
    public partial class Teavita
    {
        
        private Teavitus teavitusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Teavitus Teavitus
        {
            get
            {
                return this.teavitusField;
            }
            set
            {
                this.teavitusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://teavitus.x-road.ee")]
    public partial class TeavitaResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TeavitaRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public Xtee.Teavitus.Connector.TeavitusTeenus.XRoadClientIdentifierType client;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public Xtee.Teavitus.Connector.TeavitusTeenus.XRoadServiceIdentifierType service;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string id;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string userId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string issue;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string protocolVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://teavitus.x-road.ee", Order=0)]
        public Xtee.Teavitus.Connector.TeavitusTeenus.Teavita Teavita;
        
        public TeavitaRequest()
        {
        }
        
        public TeavitaRequest(Xtee.Teavitus.Connector.TeavitusTeenus.XRoadClientIdentifierType client, Xtee.Teavitus.Connector.TeavitusTeenus.XRoadServiceIdentifierType service, string id, string userId, string issue, string protocolVersion, Xtee.Teavitus.Connector.TeavitusTeenus.Teavita Teavita)
        {
            this.client = client;
            this.service = service;
            this.id = id;
            this.userId = userId;
            this.issue = issue;
            this.protocolVersion = protocolVersion;
            this.Teavita = Teavita;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TeavitaResponse1
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public Xtee.Teavitus.Connector.TeavitusTeenus.XRoadClientIdentifierType client;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public Xtee.Teavitus.Connector.TeavitusTeenus.XRoadServiceIdentifierType service;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string id;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string userId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string issue;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string protocolVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://teavitus.x-road.ee", Order=0)]
        public Xtee.Teavitus.Connector.TeavitusTeenus.TeavitaResponse TeavitaResponse;
        
        public TeavitaResponse1()
        {
        }
        
        public TeavitaResponse1(Xtee.Teavitus.Connector.TeavitusTeenus.XRoadClientIdentifierType client, Xtee.Teavitus.Connector.TeavitusTeenus.XRoadServiceIdentifierType service, string id, string userId, string issue, string protocolVersion, Xtee.Teavitus.Connector.TeavitusTeenus.TeavitaResponse TeavitaResponse)
        {
            this.client = client;
            this.service = service;
            this.id = id;
            this.userId = userId;
            this.issue = issue;
            this.protocolVersion = protocolVersion;
            this.TeavitaResponse = TeavitaResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ITeavitusTeenusChannel : Xtee.Teavitus.Connector.TeavitusTeenus.ITeavitusTeenus, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class TeavitusTeenusClient : System.ServiceModel.ClientBase<Xtee.Teavitus.Connector.TeavitusTeenus.ITeavitusTeenus>, Xtee.Teavitus.Connector.TeavitusTeenus.ITeavitusTeenus
    {
        
        public TeavitusTeenusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Xtee.Teavitus.Connector.TeavitusTeenus.TeavitaResponse1> Xtee.Teavitus.Connector.TeavitusTeenus.ITeavitusTeenus.TeavitaAsync(Xtee.Teavitus.Connector.TeavitusTeenus.TeavitaRequest request)
        {
            return base.Channel.TeavitaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Xtee.Teavitus.Connector.TeavitusTeenus.TeavitaResponse1> TeavitaAsync(Xtee.Teavitus.Connector.TeavitusTeenus.XRoadClientIdentifierType client, Xtee.Teavitus.Connector.TeavitusTeenus.XRoadServiceIdentifierType service, string id, string userId, string issue, string protocolVersion, Xtee.Teavitus.Connector.TeavitusTeenus.Teavita Teavita)
        {
            Xtee.Teavitus.Connector.TeavitusTeenus.TeavitaRequest inValue = new Xtee.Teavitus.Connector.TeavitusTeenus.TeavitaRequest();
            inValue.client = client;
            inValue.service = service;
            inValue.id = id;
            inValue.userId = userId;
            inValue.issue = issue;
            inValue.protocolVersion = protocolVersion;
            inValue.Teavita = Teavita;
            return ((Xtee.Teavitus.Connector.TeavitusTeenus.ITeavitusTeenus)(this)).TeavitaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public new virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
